### ISSUE TITLE
[in progress] change font to an open-source font

### ISSUE THREAD

**Issue by fab4U** [blinkenrocket/firmware#5]
Hallo Muzy!
Blinkenrocket verwendet den Zeichensatz des Hacklace2. Dieser ist NICHT mit der GPL kompatibel. Außderdem verstößt dies gleich in mehrfacher Weise gegen geltendes Recht.
Bitte setze dich umgehend mit mir in Verbindung, um diese sehr unschöne Sache zu bereinigen.
Viele Grüße
Frank

**Comment by felicitus** [comment]
https://de.wikipedia.org/wiki/Sch%C3%B6pfungsh%C3%B6he#Individualit.C3.A4t

**Comment by NoMoKeTo** [comment]
Ich würde mal dringend zu den ÖPNV-Anzeigetafeln rennen und checken ob die vielleicht auch dein Urheberrecht verletzen. Der Zeichensatz „ASCII“ wird übrigens auch von GitHub verwendet, vielleicht also direkt da einschreiten?

**Comment by fab4U** [comment]
Hallo,

ihr solltet vielleicht einmal selbst einen Zeichensatz erstellen. Dann werdet ihr merken, dass da einige Tage Arbeit drin stecken. Natürlich kann es sein, dass einzelne Zeichen mit anderen Werken gleich sind, aber nicht der gesamte Zeichensatz mitsamt allen Kommentaren im Quelltext. Da muss man eben schon etwas differenzierter hinschauen.

Muzy hat einfach nur stumpf kopiert und keinerlei schöpferische Leistung erbracht. Auch hat er die Nennung des wahren Urhebers bewusst vermieden. Das ist nicht ok.

Warum hat er nicht einfach den Zeichensatz des blinken64 benutzt? Das hätte mich nicht gestört. Insofern ist eine gewisse Böswilligkeit nicht auszuschließen.

Viele Grüße

Frank

**Comment by felicitus** [comment]
Hallo Frank,

vielleicht solltest du selbst einmal einen Namen erdenken. Dann wirst du feststellen, daß da die Leistung einiger vieler Menschen drinstecken. Natürlich kann es sein, daß einzelne Wörter mit anderen gleichen.

Du hast einfach nur stumpf kopiert und markenrechtlich geschützt.

Warum hast du nicht einfach einen anderen Namen erdacht? Das hätte uns nicht gestört. Insofern ist eine gewisse Böswilligkeit nicht auszuschließen.

Viele Grüße
Feli

**Comment by echox** [comment]
Hallo Feli,
du vergisst das der Name markenrechtlich eingetragen ist.
Es hat niemand in der entsprechenden Widerspruchsfrist (ich glaube 3 Monate) widersprochen.
Gut, das kann natuerlich daran liegen, dass niemand von der Markeneintragung gewusst hat...

**Comment by fab4U** [comment]
Hallo Timo,

ich gehe davon aus, dass Du mit Deiner Mail auf den Namen „Hacklace“ anspielst.

Leider bist Du in dieser Hinsicht nicht bzw. falsch informiert. Den Namen "Hacklace“ habe ich mir ausgedacht. Dies geschah als ich das erste mal zuhause bei mir am Rechner saß und Entwürfe für eine Schaltung, das spätere „Hacklace classic“, erstellen wollte. Dazu habe ich bei mir einen neuen Ordner angelegt und ihn „Hacklace“ genannt.

Als ich einige Tage später Muzy meine Pläne vorstellte, habe ich ihm mittgeteilt, dass ich als Arbeitstitel für das Projekt „Hacklace“ gewählt habe, und darauf hingewiesen, dass wir diesen Namen später auch noch ändern könnten, falls er ihm nicht gefällt.

Die Schaffung des Namens „Hacklace“ fand also bei mir im stillen Kämmerlein statt und daran war definitiv niemand außer mir beteiligt. Deshalb habe ich mich auch berechtigt gesehen, ihn zur Marke anzumelden. Es ist natürlich gut möglich, dass Muzy oder Leute aus dem RZL hier falsche Informationen gestreut haben, um mir zu schaden. Manche Hacker sind leider nicht sehr fair.

Viele Grüße

Frank

**Comment by muzy** [comment]
Hallo *,

da dass ganze hier gerade in einer sehr hitzigen und emotionalen Diskussion ausartet die mit vielen verschiedenen Unterstellungen übersäht ist, locke ich die Konversation erst einmal bis eine Sachliche Diskussion zu stande kommen kann.

@fab4U Ich kläre den Sachverhalt heute Abend und melde mich später hier nochmal in dem Ticket. Mir Böswilligkeit zu unterstellen ist nicht in Ordnung und entspricht in nicht der Realität. 

Übrigens: Ziel dieses Bausatzes ist es nicht, alte und unnötige Konflikte zu schüren oder wieder aufleben zu lassen. Dazu sind wir doch alle zu erwachsen. Egal ob BlinkenRocket oder Hacklace 2 oder ein anderer Bausatz: Als unser gemeinsames(!) Ziel der Maker- und Hackerspace-Community verstehe ich Kindern-, Jugendlichen und Erwachsenen das Löten, Programmieren, Reparieren und Erweitern näher zu bringen. An diesem Erfolg sollten wir in **einer** Community **gemeinsam** arbeiten.

**Comment by muzy** [comment]
Hallo *,

mit #6 wurde soeben eine neue Font bereitgestellt (http://www.fonts2u.com/pixel-operator-8.font) welche unter der SIL Open Font License steht. (Danke @elzoido!). Danke dir auch @fab4U, dass du uns auf dieses Problem aufmerksam gemacht hast!

Heute Abend werde ich die Änderungen auch in die anderen Sub-Projekte übernehmen und jeweils eine neue Version veröffentlichen. Für noch vorhandene Bausätze werde ich am Wochenende die Firmware neu flashen, damit das Problem dort entsprechend auch beseitigt ist. Es ist da ein wenig Glück im Unglück, dass zum jetzigen Zeitpunkt nur wenige der gespendeten BlinkenRockets verschenkt wurden.

Wie es zu dem Problem gekommen ist, kann ich ein knappes halbes Jahr nach dem ersten Commit leider nicht mehr nachvollziehen, wahrscheinlich habe ich die Font.h irgendwo auf meinem Rechner gefunden, der Hardware entsprechend angepasst und nicht weiter drüber nachgedacht. Es tut mir sehr leid wenn du dich dadurch angegriffen, benachteiligt oder verletzt gefühlt hast - das war nie meine Intention. Es tut mir auch sehr Leid, dass du ein Bild von mir als unfairen, böswilligen und nicht lösungsorientierten Menschen hast. Wahrscheinlich liegt das an der ein oder anderen unschönen Geschichte aus der Vergangenheit wo auf allen Seiten alles mehr als doof gelaufen ist. Allerdings sollte unsere Vergangenheit unsere Vergangenheit bleiben und alte Streitigkeiten irgendwann nichtig werden. 

Für die Zukunft sollte uns dieser Thread hier daran erinnern, dass nicht immer alles ganz rund läuft. Persönliche Probleme der Vergangenheit sollten der Vergangenheit angehören! Wenn wir, wie hier, Hand-in-Hand und sachlich ein Problem lösen, ist am Ende allen geholfen. 

Liebe Grüße,

muzy

PS: Für Dokumentationszwecke hier noch ToDos:

- [x] Pull-Request #6 mergen
- [ ] Webeditor-Font anpassen/fixen in blinkenrocket/webedit-react
- [ ] Alten WebEditor anpassen (ggf. Projekt archivieren)
- [ ] Mikrocontroller im Bestand neu flashen

PPS: Wenn du als kleine Entschuldigung einen Bausatz magst, sag mir gerne Bescheid. Ich schick dir gerne eine BlinkenRocket per Post!

PPPS: Ich habe die Konversation wieder aufgemacht. Bitte verhaltet euch exzellent zueinander und respektiert euch gegenseitig.

**Comment by soerenob** [comment]
Tolle Lösung, danke für euer Engagement!
Die Blinkenrocket hat am Wochenende Begeisterung bei unseren Stadtfestbesuchern ausgelöst und wir haben schon Anmeldungen von Jugendlichen erhalten, die bei uns ihre eigene Rocket bauen möchten. Werde die Firmware vorher flashen.

**Comment by muzy** [comment]
Ich habe mit [diesem Commit](https://github.com/blinkenrocket/firmware/commit/baa0d55f004c8dbc6ce29bfc9b76f79caaeddc4a) noch eine Notiz in die README des Projektes eingefügt, um auf dieses Problem bei alten BlinkenRocket hinzuweisen.

**Comment by muzy** [comment]
Alle ToDo items die sich in Software abbilden lassen, wurden umgesetzt. Das neu-flashen der Mikrocontroller findet am folgenden Samstag (04.06.2016) statt. Damit schließe ich dieses Issues als gelöst.
